### PR TITLE
Rebase to v3.4 and several improvements in IS plugin code

### PR DESCRIPTION
**Pull request by chrishamm**
Rebase to v3.4
Moved different cards to separate tabs
Cleaned up some of the code

Design notes:
- Do not use v-card-text outside v-card and use it only once in v-cards
- Use proper forms in general, usage of rows except for single inputs doesn't conform to standard, see https://vuetifyjs.com/en/components/forms/#usage or see sampleRateRules etc
- Add samples input value (timeout does not exist, see M956 docs -> https://duet3d.dozuki.com/Wiki/Gcode#Section_M956_Collect_accelerometer_data_and_write_to_file, now renamed to numSamples)
- It is possible to use distinct labels and values in comboboxes allowing you to save a lot of redundant recorder data values. Best to use data values only for user inputs (or mutable values) and computed values for other stuff (set v-model to a whole `axis` object rather than a letter)
- Please mark temporary code as such (e.g. via )

TODO:
- [x] Make number of samples configurable
- [x] Please add validation to the Record Profile button
- [x] If the test command returns an empty result (= success), show frequency analysis, (re?)load file, and start analysis automatically
- [x] When running analysis FFT code, look for peak and prefill frequency on IS configuration tab
- [x] When everything is working, check responsiveness for xs/sm/md/lg/xl configurations (there are browser tools for this)
- Finish german translations for IS plugin (console in dev mode outputs missing de keys), moved task here #374

### CODE REVIEW

**Comment by mfs12** [comment]
>  If the test command returns an empty result (= success), show frequency analysis, (re?)load file, and start analysis automatically

this is not yet feasible because the end of recording can't be properly detect AFAIK.

**Comment by chrishamm** [comment]
Why not? You can detect when the machine has moved to the start and end positions and when the machine state goes back to idle. It may work to send every code one by one and to await each one but the first approach would be safer.

**Comment by mfs12** [comment]
> Why not? You can detect when the machine has moved to the start and end positions and when the machine state goes back to idle. It may work to send every code one by one and to await each one but the first approach would be safer.

ok. this sounds reasonable and obvious. ;)

**Comment by chrishamm** [comment]
PR updated, new i18n call for plugins tested and working.

**Pull request merged**
